# 二、异常和引用

在这一章中，我们将探索异常和引用，这是现代面向对象编程(OOP)的两个基本方面。同步事件除外。“同步”这个词意味着它们是对代码本身事件的反应，而不是对外部事件(如信号)的反应。例如，当操作员按下键盘上的 Ctrl-C 时，一个信号被发送到正在执行的程序。异常用于以有序、符合标准的方式处理错误。当程序(或者在 PHP 中是脚本)试图执行除以零时，会引发一个异常。异常可以被引发(或*抛出*)和捕获。引发异常实际上意味着将程序控制权交给程序中用来处理这些事件的部分。像 PHP 这样的现代编程语言有办法以逻辑和有序的方式做到这一点。

### 异常情况

异常是类`Exception`或任何扩展类`Exception`的类的对象。你会记得在前一章中，继承经常被描述为类之间的“是”层次关系。摘自文档的`Exception`类的定义如下:

`Exception {
/* Properties */
protected string $message ;
protected int $code ;
protected string $file ;
protected int $line ;
/* Methods */
public __construct ([ string $message = "" [, int $code = 0
                               [, Exception $previous = NULL ]]] )
final public string getMessage ( void )
final public Exception getPrevious ( void )
final public int getCode ( void )
final public string getFile ( void )
final public int getLine ( void )
final public array getTrace ( void )
final public string getTraceAsString ( void )
public string __toString ( void )
final private void __clone ( void )
}`

因此，异常是在错误事件发生时至少包含以下信息的对象:错误消息、错误代码、抛出异常的文件以及抛出异常的行。不足为奇的是，异常对于调试程序和确保程序正确运行非常有用。或者，你可以把异常想象成一些小球，当一些“不好的”事情发生时，它们被抛出正在运行的程序，并且可以被捕获来分析发生了什么。清单 2-1 显示了一个例子。

***清单 2-1。**异常例子*

`<?php
class NonNumericException extends Exception {
    private $value;
    private $msg = "Error: the value %s is not numeric!\n";
    function __construct($value) {
        $this->value = $value;
    }
    public function info() {
        printf($this->msg, $this->value);
    }
}
try {
    $a = "my string";
    if (!is_numeric($argv[1])) {
        throw new NonNumericException($argv[1]);
    }
    if (!is_numeric($argv[2])) {
        throw new NonNumericException($argv[2]);
    }
    if ($argv[2] == 0) {
        throw new Exception("Illegal division by zero.\n");
    }
    printf("Result: %f\n", $argv[1] / $argv[2]);
}

catch(NonNumericException $exc) {
    $exc->info();
    exit(-1);
}
catch(Exception $exc) {
    print "Exception:\n";
    $code = $exc->getCode();
    if (!empty($code)) {
        printf("Erorr code:%d\n", $code);
    }
    print $exc->getMessage() . "\n";
    exit(-1);
}
print "Variable a=$a\n";
?>`

当使用不同的命令行参数执行时，该脚本会产生以下输出:

`./script3.1.php 4 2

Result: 2.000000
Variable a=my string

./script3.1.php 4 A

Error: the value A is not numeric!

./script3.1.php 4 0

Exception:
Illegal division by zero.`

这个小脚本充满了关于异常的注意事项。`$argv`数组是一个预定义的全局数组，包含命令行参数。还有一个预定义的全局变量`$argc`，包含命令行参数的数量，就像 C 语言中一样。现在，让我们把注意力放在异常和它们的语法上。首先，我们定义了一个`Exception`类，它本质上忽略了`Exception`类的现有结构，甚至没有在扩展类的构造函数中调用`parent::__construct`方法。这被认为不是一个好的编程实践，这里只是作为一个例子。其结果是我们的异常没有熟悉的`getMessage`和`getCode`函数，这将使它们更难使用和调用。

异常的通常语义不适用于我们的类，例如，如果有人决定使用`getMessage()`方法，这可能会导致问题。接下来，我们创建了一个`try`块，其中可能会出现异常。我们正在测试紧随`try`块之后的`catch`块中的异常，也称为异常处理程序。`try`块不是普通的作用域块；在`try`块内定义的变量将保持在块外定义。特别是，当 4 除以 2 时，变量`$a`在第一次执行中的除法完成后被打印。

其次，观察`throw`语句的语法:抛出的是一个异常对象。`catch`块中的异常处理程序非常类似于接受一个参数的函数，一个异常对象。异常处理程序的顺序也很重要:PHP 会将手头的异常传递给第一个能够处理所抛出类型的异常的异常处理程序。异常类型`Exception`的处理程序必须总是排在最后，因为它是一个“通吃”程序，可以捕捉任何类型的异常。

当抛出异常时，PHP 会寻找第一个适用的处理程序并使用它。如果默认异常类的处理程序放在`NonNumericException`类的处理程序之前，后者将永远不会被执行。

异常处理程序块，或`catch`块，看起来像函数。这不是巧合。PHP 还有一个叫做`set_exception_handler`的“神奇”方法，在这个方法中可以设置一个“捕获所有”异常处理程序来捕获所有未被捕获的异常。让我们重写[清单 2-1](#list_2_1) 中的脚本(参见[清单 2-2](#list_2_2) )。

***清单 2-2。**改写的脚本来自[清单 2-1](#list_2_1)T5】*

`<?php
function dflt_handler(Exception $exc) {
    print "Exception:\n";
    $code = $exc->getCode();` 
`    if (!empty($code)) {
        printf("Erorr code:%d\n", $code);
    }
    print $exc->getMessage() . "\n";
    exit(-1);
}
set_exception_handler('dflt_handler');

class NonNumericException extends Exception {
    private $value;
    private $msg = "Error: the value %s is not numeric!\n";
    function __construct($value) {
        $this->value = $value;
    }
    public function info() {
        printf($this->msg, $this->value);
    }
}
try {
    if (!is_numeric($argv[1])) {
        throw new NonNumericException($argv[1]);
    }
    if (!is_numeric($argv[2])) {
        throw new NonNumericException($argv[2]);
    }
    if ($argv[2] == 0) {
        throw new Exception("Illegal division by zero.\n");
    }
    printf("Result: %f\n", $argv[1] / $argv[2]);
}

catch(NonNumericException $exc) {
    $exc->info();
    exit(-1);
}
?>`

这个脚本的结果将与来自[清单 2-1](#list_2_1) 的原始脚本的结果相同。在`set_exception_handler`函数中声明的异常处理程序是一个接受类`Exception`的一个参数的函数，在所有声明的异常处理程序之后执行:

`./script3.1b.php 4 A
Error: the value A is not numeric!`

这显然是来自我们的`NonNumericException`处理程序，而不是来自默认处理程序。如果在执行 script3.1b.php 时用 0 代替字母“A ”,我们会得到原来的结果:

`./script3.1b.php 4 0
Exception:
Illegal division by zero.`

这是默认的异常处理程序。默认异常处理程序什么时候有用？它们在处理其他人写的类时特别有用，比如上一章的`SplFileObject`类。如果出错，`SplFileClass`的对象将抛出`Exception`类的异常，就像 ADOdb 一样。

![images](img/square.jpg) **注意:当出现错误时，PEAR 库中的**类将抛出`PEAR_Exception`类的对象。`PEAR_Exception`拥有普通`Exception`类的所有元素，变量`$trace`被添加到 lot 中。`PEAR_Exception`也会尝试显示堆栈跟踪，当它被抛出和捕获时。

清单 2-3 是一个试图使用`SplFileObject`类打开一个不存在的文件的脚本的例子。还有一个默认的异常处理程序，它将捕捉由`SplFileObject`抛出的异常，尽管在代码中没有显式的`try { ..} catch {...}`块。

***清单 2-3。**一个脚本试图使用`SplFileObject`类*打开一个不存在的文件的例子

`<?php
function dflt_handler(Exception $exc) {
    print "Exception:\n";
    $code = $exc->getCode();
    if (!empty($code)) {
        printf("Erorr code:%d\n", $code);
    }
    print $exc->getMessage() . "\n";
    print "File:" . $exc->getFile() . "\n";
    print "Line:" . $exc->getLine() . "\n";
    exit(-1);
}
set_exception_handler('dflt_handler');
$file = new SplFileObject("non_existing_file.txt", "r");
?>`

执行该脚本时，结果如下所示:

`Exception:
SplFileObject::__construct(non_existing_file.txt): failed to open stream: No such file or directory
File:/home/mgogala/work/book/Chapter3/script3.2.php
Line:15`

当处理别人写的类时，默认的`catch all`处理程序可能是一个非常有用的工具，尽管它是不加选择的。默认的`catch all`处理程序将处理所有未被捕获的异常，它通常用于终止程序并允许简单的调试。当然，程序员可能希望安排对某些情况的特殊处理，并做类似这样的事情:

`try {
    $file = new SplFileObject("non_existing_file.txt", "r");
}
catch (Exception $e) {
    $file=STDIN;
}`

如果打开文件进行读取有问题，则返回标准输入。当然，这不再是类`SplFileObject`的对象，所以程序员必须考虑可能的结果。由于默认的`catch all`处理程序是最后执行的，对于没有被其他任何处理程序捕捉到的异常，谨慎处理并编写我们自己的异常处理程序没有任何障碍。

还有一点要提:异常的嵌套。PHP 不支持它，除非`try`块也是嵌套的。换句话说，在这种情况下，如果从`ExcA`的处理程序中调用异常，那么`ExcB`的处理程序将不会被调用:

`class ExcA extends Exception {...}
class ExcB extends Exception {...}
try {... throw new ExcA(..) }
catch(ExcA $e) {  throw new ExcB(); }
catch(ExcB $e) {  // Will not be called, if thrown from the ExcA }`

嵌套异常的唯一方法是嵌套`try`块。关于异常嵌套，PHP5 与 Java 或 C++相同。

### 引用

PHP 中另一种重要的对象称为引用。PHP 引用不是指针。与 Perl 不同，PHP 没有可用于通过解引用来寻址对象的“引用”类型。在 PHP 中，“引用”一词只是对象的另一个名称。考虑清单 2-4 中的脚本。

***清单 2-4。**引用是 PHP 中的对象*

`<?php
class test5 {
    private $prop;
    function __construct($prop) {
        $this->prop = $prop;
    }
    function get_prop() {
        return ($this->prop);
    }
    function set_prop($prop) {
        $this->prop = $prop;
    }
}
function funct(test5 $x) {
    $x->set_prop(5);
}` `$x = new test5(10);
printf("Element X has property %s\n", $x->get_prop());
funct($x);
printf("Element X has property %s\n", $x->get_prop());

$arr = range(1, 5);
foreach ($arr as $a) {
    $a*= 2;
}
foreach ($arr as $a) {
    print "$a\n";
}
?>`

执行该脚本时，会产生以下输出:

`Element X has property 10
Element X has property 5
1
2
3
4
5`

对于一个对象变量`$x`，其值通过在方法`funct`中操作而改变，对于数组变量`$arr`，其值不会通过在`foreach`循环中操作元素而改变。这个令人困惑的谜题的答案在于 PHP 通过复制传递参数。这意味着，对于数字、字符串或数组之类的非对象类型，将创建另一个完全相同的对象实例，而对于对象类型，将创建一个引用或对象的另一个名称。当类`test5`的参数`$x`被传递给方法`funct`时，相同对象的另一个名称被创建。通过操纵新变量，我们操纵了原始对象的内容，因为新变量只是现有对象的另一个名称。详情请参阅第一章。虽然 PHP 不像 Perl，不允许直接访问引用，但它仍然允许在一定程度上控制如何复制对象。让我们通过引用来介绍复制(见[清单 2-5](#list_2_5) )。

***清单 2-5。**参照复制*

`<?php
print "Normal assignment.\n";
    $x = 1;
    $y = 2;
    $x = $y;
    $y++;
    print "x=$x\n";
print "Assignment by reference.\n";
    $x = 1;
    $y = 2;
    $x = & $y;
    $y++;
    print "x=$x\n";
?>`

执行该脚本时，结果如下所示:

`Normal assignment.
x=2
Assignment by reference.
x=3`

这个脚本由两部分组成:普通赋值和引用赋值。在第一部分中，进行常规赋值，创建变量`$y`的新副本并将其赋值给`$x`，丢弃之前的内容。增加`$y`对变量`$x`完全没有影响。第二部分，通过引用做赋值，变量`$x`之前的内容也被扔掉了，但是变量被做成了变量`$y`的别名(又名“引用”)。将变量`$y`增加 1 在变量`$x`中也是可见的，变量`$x`显示的是`3`而不是`2`，赋值后是`$x`的值。

同样的操作也可以应用于循环。在[清单 2-4](#list_2_4) 中，我们有以下代码片段:

`$arr = range(1, 5);
foreach ($arr as $a) {
    $a*= 2;
}
foreach ($arr as $a) {
    print "$a\n";`

结果是从 1 到 5 没有变化的数字。现在让我们使用引用操作符`&`重写这段代码:

`$arr = range(1,5);
foreach ($arr as &$a) {
        $a *= 2;
}
print_r($arr);`

结果是一个改变的数组:

`Array
(
    [0] => 2
    [1] => 4
    [2] => 6
    [3] => 8
    [4] => 10
)`

换句话说，通过将`&`加到`$a`，我们没有创建数组元素的副本，就像在表达式`foreach($arr as $a)`中所做的那样。相反，我们创建了对数组成员的引用，这意味着我们在循环中对`$a`所做的任何事情都将修改实际的数组成员，而不是副本。不可能引用一个函数。

![images](img/square.jpg) **注意**使用`foreach`循环的驱动数组时要小心。如果代码更改了驱动数组，可能会导致不可预测和意外的结果。

然而，从函数返回引用并通过引用传递参数是可能的。当希望函数能够修改原始变量时，通过引用传递参数。语法与循环相同:通过引用传递的变量只是简单地以&字符(`&`)为前缀。:[清单 2-6](#list_2_6) 是一个小例子。

***清单 2-6。**可以从函数中返回引用，并通过引用传递参数*

`<?php
$a = 5;
function f1($x) {
    $x+= 3;
    print "x=$x\n";
}
function f2(&$x) {
    $x+= 3;
    print "x=$x\n";
}

f1($a);
print "a=$a\n";
f2($a);
print "a=$a\n";
?>`

当执行这个小片段时，结果如下所示:

`x=8
a=5
x=8
a=8`

当调用函数`f1`时，参数通过值传递。函数中的`print`语句打印了值`8`，但是原始变量没有被修改；它保留了值`5`。当函数`f2`被调用时，原始变量被修改，从变量`a`的最后一次打印输出可以看出。

引用也可以从函数中返回。这不应该是为了提高性能，因为 PHP 会自动这么做。重申一下:引用只是现有变量的另一个名字。引用可以用来绕过关键字`private`或`protected`提供的可见性保护。[清单 2-7](#list_2_7) 就是一个例子。

***清单 2-7。**引用可用于规避能见度保护*

`<?php
class test6 {
    private $x;
    function __construct($x = 10) {
        $this->x = $x;
    }` `    function &get_x() {  // Observe the "&" in the function![images](img/U002.jpg)
declaration
        return $this->x;
    }
    function set_x($x) {
        $this->x = $x;
    }
}
$a = new test6();
$b = &$a->get_x(); // $b is a reference to $x->a. It![images](img/U002.jpg)
circumvents protection
                                // provided by the "private"![images](img/U002.jpg)
qualifier.
print "b=$b\n";
$a->set_x(15);
print "b=$b\n";        // $b will change its value, after![images](img/U002.jpg)
calling "set_x"
$b++;
print '$a->get_x()='.$a->get_x() . "\n"; // $a->x will change![images](img/U002.jpg)
its value after $b being
                                                             ![images](img/U002.jpg)
  // incremented
?>`

执行时，输出如下所示:

`b=10
b=15
$a->get_x()=16`

这里，变量`$b`变成了对`$a->x`的引用，T1 是类`test6`的私有成员。这是通过将函数`get_x()`声明为返回引用来实现的。当然，对私有变量的公共引用破坏了可见性控件的目的。。通过引用返回值通常是一件非常奇特的事情。应该仔细考虑，因为很容易通过从函数返回引用来允许非预期的访问。

### 总结

在这一章中，你学习了 PHP 中的异常和引用。在其他现代编程语言中也可以找到这两种语言。异常的目的是为错误处理提供一个简单明了的机制；引用的目的主要是为了提高代码执行速度，偶尔也是为了让一些编程技巧成为可能。这两种语言元素都非常有用，可以为程序员提供许多好处。异常处理程序使错误检查变得更加优雅，这将在关于数据库集成的章节中展示。